SanalDenemem.MvcWebUI/Models/ExamResultDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SanalDenemem.MvcWebUI.Models
{
    public class ExamResultDetails
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string  UserName { get; set; }
        public double Score { get; set; }
        public double TotalPoint { get; set; }
    }
}

SanalDenemem.MvcWebUI/Controllers/AdminManagerController.cs
using Microsoft.AspNet.Identity;
using SanalDenemem.MvcWebUI.Identity;
using SanalDenemem.MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SanalDenemem.MvcWebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminManagerController : BaseController
    {
        public ActionResult Index()
        {
            return View(RoleManager.Roles.ToList());
        }

        public ActionResult Edit(string id)
        {
            var role = RoleManager.FindById(id);
            var member = new List<ApplicationUser>();
            var nonmember = new List<ApplicationUser>();

            foreach (var user in UserManager.Users.ToList())
            {
                var list = UserManager.IsInRole(user.Id, role.Name) ? member : nonmember;
                list.Add(user);
            }

            return View(new RoleUpdate()
            {
                Role = role,
                Members = member,
                NonMembers = nonmember
            });

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RoleAdminInfo model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (var userid in model.AddToIds ?? new string[] { })
                {
                    result = UserManager.AddToRole(userid, model.Name);
                    if (!result.Succeeded)
                    {
                        return View("Eror", new string[]
                        {
                            " hata oluştu."
                        });
                    }
                }

                foreach (var userid in model.DeleteToIds ?? new string[] { })
                {
                    result = UserManager.RemoveFromRole(userid, model.Name);

                    if (!result.Succeeded)
                    {
                        return View("Eror", new string[]
                        {
                            " hata oluştu."
                        });
                    }
                }


                return RedirectToAction("Index");
            }
            else
            {
                return View("Eror", new string[]
                {
                    " hata oluştu."
                });
            }
        }

        public ActionResult Delete(string id)
        {
            var user = UserManager.FindById(id);
            var result = UserManager.Delete(user);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Eror", new string[] { "hata olutu" });
            }
        }
    }
}

SanalDenemem.MvcWebUI/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SanalDenemem.MvcWebUI.Entity;

namespace SanalDenemem.MvcWebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class ContactController : BaseController
    {
       
        public ActionResult Index()
        {
            return View(db.Contacts.ToList());
        }

        // GET: Contact/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Contact contact = db.Contacts.Find(id);
        //    if (contact == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(contact);
        //}

        [AllowAnonymous]
        // GET: Contact/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contact/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FullName,Email,Content,Subject")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Contacts.Add(contact);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return View(contact);
        }

        // GET: Contact/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Contact contact = db.Contacts.Find(id);
        //    if (contact == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(contact);
        //}

        //// POST: Contact/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,FullName,Email,Content,Subject")] Contact contact)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(contact).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(contact);
        //}

        // GET: Contact/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Contact contact = db.Contacts.Find(id);
        //    if (contact == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(contact);
        //}

        // POST: Contact/Delete/5
      
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            db.Contacts.Remove(contact);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SanalDenemem.MvcWebUI/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SanalDenemem.MvcWebUI.Entity;

namespace SanalDenemem.MvcWebUI.Controllers
{
    public class TaskController : BaseController
    {
        

        // GET: Task/Create
        public ActionResult Create(int id)
        {
            ViewBag.MemberId =id;
            return View();
        }

        // POST: Task/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Task task,int id)
        {
            task.MemberId = id;
            var member = db.Members.FirstOrDefault(i => i.Id == id);
            if (ModelState.IsValid)
            {
                db.Tasks.Add(task);
                db.SaveChanges();
                return RedirectToAction("Profile", "Members",new { id=member.UserId} );
            }

            ViewBag.MemberId = id;
            return View(task);
        }

        // GET: Task/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            ViewBag.userId = task.MemberId;
            if (task == null)
            {
                return HttpNotFound();
            }
           // ViewBag.MemberId = new SelectList(db.Members, "Id", "UserId", task.MemberId);
            return View(task);
        }

        // POST: Task/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Task task)
        {
            if (ModelState.IsValid)
            {
                var member = db.Members.FirstOrDefault(i => i.Id == task.MemberId);
              
                db.Entry(task).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Profile", "Members", new { id = member.UserId });
            }
            ViewBag.userId = task.MemberId;
            return View(task);
        }

        // GET: Task/Delete/5
      

        // POST: Task/Delete/5
        
   
        public ActionResult Delete(int id)
        {          
            Task task = db.Tasks.Find(id);
            
           var userId = task.MemberId;
           var member = db.Members.FirstOrDefault(i => i.Id == userId);
            db.Tasks.Remove(task);
            db.SaveChanges();
            return RedirectToAction("Profile","Members",new {id=member.UserId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SanalDenemem.MvcWebUI/Views/Shared/_ExamResult.cshtml
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
@model IEnumerable<SanalDenemem.MvcWebUI.Entity.MemberExam>

<div class="row">
    
    @foreach (var item in Model)
     {
            <div class="col-md-4 col-sm-6">
                @if (item.CorrectCount > item.FailCount)
                {
                    <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                        <div class="card-header">sınav sonucu</div>
                        <div class="card-body">
                            <h5 class="card-title"> net sayısı: @item.Score</h5>
                            <ul>
                                <li>dogru sayısı:@item.CorrectCount</li>
                                <li>dogru sayısı:@item.FailCount</li>
                                @Html.ActionLink("sınavNo", "ExamResultDetails", "Members", new { Id = item.Id }, null)

                            </ul>
                        </div>
                    </div>
                }
                else
                {
                    <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                        <div class="card-header">sınav sonucu</div>
                        <div class="card-body">
                            <h5 class="card-title"> net sayısı: @item.Score</h5>
                            <ul>
                                <li>dogru sayısı:@item.CorrectCount</li>
                                <li>dogru sayısı:@item.FailCount</li>
                                @Html.ActionLink("sınavNo", "ExamResultDetails", "Members", new { Id = item.Id }, null)
                            </ul>
                        </div>
                    </div>
                }

            </div>
     }
</div>

SanalDenemem.MvcWebUI/Views/Shared/_ExamResultDetails.cshtml
@model List<SanalDenemem.MvcWebUI.Models.ExamResultDetails>

<link href="~/Content/Plugins/dataTableJquery/jquery.dataTables.min.css" rel="stylesheet" />
<table id="myTable" class="table table-bordered">
    <thead>
        <tr>
            <th>Sıralama</th>
            <th>İsim</th>
            <th>Soyisim</th>
            <th>Kullanıcı Adı</th>
            <th>Puan</th>
        </tr>
    </thead>
    @{ 

        int sira = 1;
    }
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@sira</td>
            <td>@item.Name</td>
            <td>@item.Surname</td>
            <td>@item.UserName</td>
            <td>@item.TotalPoint</td>
            @{
                sira = sira + 1;
            }
            
        </tr>
                }
    </tbody>
</table>

<script src="~/Content/Plugins/dataTableJquery/jquery.dataTables.min.js"></script>

SanalDenemem.MvcWebUI/Views/Shared/_Layout.cshtml
@{ 
   var logInUser= (SanalDenemem.MvcWebUI.Identity.ApplicationUser)Session["LogonUser"];
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="~/Content/Images/favicon.ico">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    
    <!-- Bootstrap core CSS -->
    <link href="~/Content/Plugins/bootstrap-4.5.2-dist/css/bootstrap.min.css" rel="stylesheet" />

    <style>
        body {
            padding-top: 3.5rem;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-danger">
        @Html.ActionLink("SANALDENEMEM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    @if (Request.IsAuthenticated)
                    {
                        var logId = User.Identity.Name;
                        if (logInUser!= null)
                        {
                            logId = logInUser.Id;
                        }
                    <a href="@Url.Action("Profile","Members",new { id =logId })">
                        Profil                       
                    </a>
                       
                    }


                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <main role="main">

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    @RenderBody()
                </div>
               
            </div>
            <hr>
        </div>
    </main>
    <footer class="container">
        <p>&copy; Company 2017-2018</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    @*<script src="~/Content/Plugins/vendor/popper.min.js"></script>*@
    <script src="~/Content/Plugins/bootstrap-4.5.2-dist/js/bootstrap.min.js"></script>
</body>
</html>

SanalDenemem.MvcWebUI/Views/Shared/_TemplateLayout.cshtml
@{
    var logInUser = (SanalDenemem.MvcWebUI.Identity.ApplicationUser)Session["LogonUser"];
}
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @*<meta name="viewport" content="initial-scale=0.1">*@
    <meta name="description" content="Online exam, çevrimiçi sınav , online sınav, sınavlar, online kurs" />
    <meta name="keywords" content="Online exam, çevrimiçi sınav , online sınav, sınavlar, online kurs" />
    <link rel="apple-touch-icon" href="~/Content/edutemplate/images/ikon.ico" />
    <link rel="icon" type="image/ico" href="~/Content/edutemplate/images/ikon.ico" />

    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="~/Content/edutemplate/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/Content/edutemplate/css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/Content/edutemplate/css/bootstrap.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/Content/edutemplate/css/magnific-popup.css">

    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="~/Content/edutemplate/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/edutemplate/css/owl.theme.default.min.css">

    <!-- Flexslider  -->
    <link rel="stylesheet" href="~/Content/edutemplate/css/flexslider.css">

    <!-- Pricing -->
    <link rel="stylesheet" href="~/Content/edutemplate/css/pricing.css">

    <!-- Theme style  -->
    <link rel="stylesheet" href="~/Content/edutemplate/css/style.css">

    <!-- Modernizr JS -->
    <script src="~/Content/edutemplate/js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <script type="text/javascript">
(function () {
        var options = {
            whatsapp: "+905510607872", // WhatsApp numaranızı buraya girin
            call_to_action: "Merhaba, bize ulaşmak için tıklayın ?", // Görünecek metin
            position: "left", // Position may be 'right' or 'left'
        };
        var proto = document.location.protocol, host = "whatshelp.io", url = proto + "//static." + host;
        var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = url + '/widget-send-button/js/init.js';
        s.onload = function () { WhWidgetSendButton.init(host, proto, options); };
        var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
    })();</script>


</head>
<body >

    <div class="fh5co-loader"></div>

    <div id="page">
        <nav class="fh5co-nav" role="navigation">
            <div class="top" style="background-color:lightblue">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 text-right">
                            <ul class="site">
                                <li><a href="https://www.facebook.com/sanaldenemem/"><i class="icon-facebook2"></i></a></li>
                                <li><a href="https://twitter.com/sanaldenemem"><i class="icon-twitter2"></i></a></li>
                                <li><a href="https://www.instagram.com/sanaldenemem/"><i class="icon-instagram"></i></a></li>
                                <li><a href="https://www.youtube.com/channel/UC7cg94tTqM5S3W6kIt3wr7Q"><i class="icon-youtube"></i></a></li>

                            </ul>

                            <ul class="fh5co-social">

                                @if (Request.IsAuthenticated && User.IsInRole("admin"))
                                {
                                    
                                    <li class="btn-cta"><a style="color:whitesmoke" href="@Url.Action("Index", "AdminManager", new { area = "" })"><span>Admin Paneli</span></a></li>
                                }
                                @if (Request.IsAuthenticated)
                                {
                                    var logId = User.Identity.Name;
                                    if (logInUser != null)
                                    {
                                        logId = logInUser.Id;
                                    }
                                    if (!(User.IsInRole("admin")))
                                    {
                                        <li class="btn-cta">
                                            <a style="color:whitesmoke" href="@Url.Action("Profile","Members",new { id =logId })"><span>Profil</span></a>
                                        </li>
                                    }
                                    <li class="btn-cta">
                                        <a style="color:whitesmoke" href="@Url.Action("Logout","Account")"><span>Çıkış</span></a>
                                    </li>
                                }
                                else
                                {
                                    <li class="btn-cta"><a href="@Url.Action("Login","Account")"><span>Giris Yap</span></a></li>
                                    <li class="btn-cta"><a href="@Url.Action("Register","Account")"><span>Kayit ol</span></a></li>
                                }
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
            <div class="top-menu" style="background-color:white">
                <div class="container" >
                    <img  class="img-responsive" align="left"src="~/Content/Images/banner.png"style="background-color:white;"width="518" height="90" />

                </div>
            </div>
            <div class="top-menu" style="background-color:#202c45">
                <div class="container">
                    <div class="row">

                        <div class="col-xs-push-12 text-sm-center menu-1 ">
                            <ul>
                                <li class="active"><a style="color:whitesmoke ; font-size:20px" href="@Url.Action("Index","Home")">Anasayfa</a></li>
                                <li><a style="color:whitesmoke; font-size:20px" href="@Url.Action("ExamTypes","Home")">Denemeler</a></li>
                                <li><a style="color:whitesmoke; font-size:20px" href="@Url.Action("Pricing","Home")">Üyelik Paketleri</a></li>
                                <li><a style="color:whitesmoke; font-size:20px" href="@Url.Action("Blog","Home")">Blog</a></li>
                                <li><a style="color:whitesmoke; font-size:20px" href="@Url.Action("About","Home")">Hakkımızda</a></li>
                                <li><a style="color:whitesmoke; font-size:20px" href="@Url.Action("Create","Contact")">İletişim</a></li>

                               

                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </nav>

        <div id="mainsection">

            @RenderBody()

        </div>

        <footer id="fh5co-footer" role="contentinfo" style="background-image: url(~/Content/edutemplate/images/img_bg_4.jpg);">
            <div class="overlay"></div>
            <div class="container">
                <div class="row row-pb-md">
                    <div class="col-md-4 fh5co-widget">
                        <h3>Sanaldenemem.com</h3>
                        <p>Tüm öğrencilerin aynı anda eşit şekilde ölçülebilmesini sağlayan kağıt , zaman ve para tasarrufu sağlayan girişimdir.</p>
                    </div>


                    <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1 fh5co-widget">
                        <h3> Menü</h3>
                        <ul class="fh5co-footer-links">
                            <li><a href="@Url.Action("Index","Home")">Anasayfa</a></li>
                            <li><a href="@Url.Action("Exams","Home")">Sınavlar</a></li>
                            <li><a href="@Url.Action("Pricing","Home")">Üyelik Paketleri</a></li>
                            <li><a href="@Url.Action("Blog","Home")">Blog</a></li>
                            <li><a href="@Url.Action("About","Home")">Hakkımızda</a></li>
                        </ul>
                    </div>


                    <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1 fh5co-widget">
                        <h3>ÜYELİK İŞLEMLERİ</h3>
                        <ul class="fh5co-footer-links">
                            <li><a href="@Url.Action("Register","Account")">Kayıt Ol</a></li>
                            <li><a href="@Url.Action("Login","Account")">Giriş Yap</a></li>

                        </ul>
                    </div>

                    <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1 fh5co-widget">
                        <h3>İLETİŞİM BİLGİLERİ</h3>
                        <ul class="fh5co-footer-links">
                            <li><a href="mailto:info@sanaldenemem.com">info@sanaldenemem.com</a></li>
                            <li><a href="https://sanaldenemem.com/">www.sanaldenemem.com</a></li>

                        </ul>
                    </div>
                </div>

                <div class="row copyright">
                    <div class="col-md-12 text-center">
                        <p>
                            <small class="block">&copy; 2020 Tüm hakları saklıdır.</small>

                        </p>
                    </div>
                </div>

            </div>
        </footer>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>

    <!-- jQuery -->
    <script src="~/Content/edutemplate/js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="~/Content/edutemplate/js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/edutemplate/js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="~/Content/edutemplate/js/jquery.waypoints.min.js"></script>
    <!-- Stellar Parallax -->
    <script src="~/Content/edutemplate/js/jquery.stellar.min.js"></script>
    <!-- Carousel -->
    <script src="~/Content/edutemplate/js/owl.carousel.min.js"></script>
    <!-- Flexslider -->
    <script src="~/Content/edutemplate/js/jquery.flexslider-min.js"></script>
    <!-- countTo -->
    <script src="~/Content/edutemplate/js/jquery.countTo.js"></script>
    <!-- Magnific Popup -->
    <script src="~/Content/edutemplate/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/edutemplate/js/magnific-popup-options.js"></script>
    <!-- Count Down -->
    <script src="~/Content/edutemplate/js/simplyCountdown.js"></script>
    <!-- Main -->
    <script src="~/Content/edutemplate/js/main.js"></script>
    <script>
        var d = new Date(new Date().getTime() + 1000 * 120 * 120 * 2000);

        // default example
        simplyCountdown('.simply-countdown-one', {
            year: d.getFullYear(),
            month: d.getMonth() + 1,
            day: d.getDate()
        });

        //jQuery example
        $('#simply-countdown-losange').simplyCountdown({
            year: d.getFullYear(),
            month: d.getMonth() + 1,
            day: d.getDate(),
            enableUtc: false
        });
    </script>
</body>
</html>

SanalDenemem.MvcWebUI/Views/Shared/_profilLayout.cshtml
@{
    var logInUser = (SanalDenemem.MvcWebUI.Identity.ApplicationUser)Session["LogonUser"];
}

SanalDenemem.MvcWebUI/Views/Shared/_taskList.cshtml
@model IEnumerable<SanalDenemem.MvcWebUI.Entity.Task>



<p>
   

    <a href="@Url.Action("Create","Task",new {id=ViewBag.id})" >
        <i class="glyphicon glyphicon-bookmark"></i>
        Görev Oluştur
    </a>
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Done)
        </th>
        <th></th>
    </tr>
    @if (ViewBag.count != 0)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @if (item.Done == true)
                    {
                        <i class="	glyphicon glyphicon-ok-circle"></i>
                    }
                    else
                    {
                        <i  class="	glyphicon glyphicon-remove-circle"></i>
                    }
                </td>
                <td>
                    <a href="@Url.Action("Edit","Task", new { id = item.Id })">Düzenle</a> |
                    <a href="@Url.Action("Delete","Task", new { id = item.Id })">Sil</a>
                </td>
            </tr>
        }
    }
    else
    {
        <tr>
            <td colspan="4" style="text-align: center;">Yapılacaklar Listesi Boş</td>
        </tr>

    }


</table>